### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by RayPS** [danieleborgo/OctoPrint-GPIOStatus#1]
Thanks for making such an amazing plugin for OctoPrint!
It's super useful for advanced users like us and I enjoy it!
However, I had some feature request for this plugin.

1. Accessible as a panel like other plugins do. GPIO Status is used very frequently, it's difficult to check through settings window every time.
2. Ability to describe/name/define a pin. So we can remember what's attached to the pin.
3. An option to toggle between BOARD/BCM pin numbering. (Physical Pin)
4. An option to hide power pins in list view. (3V3/5V/GND) or we can call it "Show GPIO pins only".
![Group 2](https://user-images.githubusercontent.com/1941540/148786074-5748305c-4191-4358-891b-ac284bbc4c4b.png)

**Comment by InoSiX** [comment]
I would like to double up on the thanks here! Great idea and interesting it took so long for someone to recognize a use case for this!

I would also like to suggest all 4 of the items mentioned here. These would be great additions.

**Comment by danieleborgo** [comment]
Thank you both for your appreciation.
Yesterday I implemented points 1, 3, and 4, I published these few minutes ago.
I'm definitely going to start working on feature 2, it is a very interesting idea.

![image](https://user-images.githubusercontent.com/26750445/148947632-be4f22a9-cb8a-4722-ae52-710eb19faf9b.png)

**Comment by InoSiX** [comment]
> 3\. option to toggle between BOARD/BCM pin numbering. (Physical Pin)

Dope dude! Great turn around time. I imagine this plugin being adopted rapidly. Thanks for your work!

**Comment by danieleborgo** [comment]
I implemented also feature 2. I just uploaded the code.

**Comment by InoSiX** [comment]
Work like yours makes Octoprint singlehandedly the best upgrade for a 3D printer. Seriously. Thanks.
