### ISSUE TITLE
With this plugin enabled, GPIO control stops working

### ISSUE THREAD

**Issue by omega015** [danieleborgo/OctoPrint-GPIOStatus#3]
With this plugin enabled, GPIO control and PSU control stops working (no psu control button and doesnt change gpio state). The moment I disable GPIOStatus those two work again. When enabled the power icon / lightening bolt no longer shows and a big emergency stop button appears (along with the one that was already there) So it seems to affect that too (at least visually).

OctoPrint 1.7.2
OctoPi 0.17.0
PSU Control (1.0.6) (with PSU Control - RPi.GPIO (1.0.4))
GPIO Control (1.0.8)
Simple Emergency Stop (1.0.5)

All up to date.

**Comment by danieleborgo** [comment]
We are using the same OctoPrint version but I need to test more in details GPIO Status with these ones.

**Comment by danieleborgo** [comment]
Have you check if there are any error in the OctoPrint logger files?

**Comment by omega015** [comment]
No warnings or errors only generic info logs about everything starting up etc...

**Comment by InoSiX** [comment]
Hiya,
For what it is worth, the digital (open/close) contacts I have on my RPI4 still work with this installed.

**Comment by omega015** [comment]
@InoSiX Are you using any of the other plugins at the same time? specifically PSU Control (1.0.6) (with PSU Control - RPi.GPIO (1.0.4)) or GPIO Control (1.0.8)?

**Comment by InoSiX** [comment]
PSU Control (1.0.6) + PSU Control - GPIO (1.0.4), indeed, yes. I'm currently using it to turn on/off a solid state (3v) relay to power the printer. I can confirm it works on PIN 23, at the very least.

**Comment by danieleborgo** [comment]
> PSU Control (1.0.6) + PSU Control - GPIO (1.0.4), indeed, yes. I'm currently using it to turn on/off a solid state (3v) relay to power the printer. I can confirm it works on PIN 23, at the very least.

I'm trying to figure out what is going on. With this do you mean GPIO23 or physical pin 23?

**Comment by omega015** [comment]
I cannot comment on InoSix but for my problem I am setup to control GPIO 17 / Pin 11 as my power switch.

**Comment by danieleborgo** [comment]
@omega015 Could you try to uninstall this plugin and redo the installation with the newest version?

**Comment by omega015** [comment]
@danieleborgo Looks like the update has resolved this issue, thank you. I notice that all status are stuck on updating though, should I log this as a separate issue?

**Comment by danieleborgo** [comment]
> @danieleborgo Looks like the update has resolved this issue, thank you. I notice that all status are stuck on updating though, should I log this as a separate issue?

Is your problem similar to [this issue](https://github.com/danieleborgo/OctoPrint-GPIOStatus/issues/4)?

**Comment by danieleborgo** [comment]
@omega015 If your problem is similar to that issue, can I close this one?
Thank you

**Comment by omega015** [comment]
Hi @danieleborgo sorry for the delay I am traveling and haven't had chance to compare but yes please close this one and I'll look at the other issue and see if that relates to mine or not.

Thank you for your work.
