### ISSUE TITLE
GPIO Status according to access control

### ISSUE THREAD

**Issue by d-faure** [danieleborgo/OctoPrint-GPIOStatus#5]
Please provide a bind to the octoprint access control features, that admins could choose to let others getting the GPIO status or not.

**Comment by danieleborgo** [comment]
Hi,
do you mean that you want a way to hide the status to non admin users?

**Comment by d-faure** [comment]
That's almost it. Getting (or changing) the status of GPIO pins should be allowable to specific user groups.

**Comment by danieleborgo** [comment]
This plugin just allows to get GPIO data and this type of information is not even protected by _sudo_. Do you have any reason to need it?
